<#
.SYNOPSIS
    Prepare a capture bundle for use in the OpenSCAD WASM Playground.

.DESCRIPTION
    Takes a Phase 2 capture bundle directory and creates a playground-ready/
    subdirectory containing:
    - scad-source.scad with -D parameter overrides appended as variable
      assignments (since the playground has no CLI -D flag support)
    - All companion files in their original directory structure

    Optionally, with -InlineCompanion, produces a single self-contained SCAD
    file by reading the critical companion file and embedding it as a comment
    block at the top for manual inlining.

.PARAMETER BundleDir
    Name of the capture bundle directory (e.g., "bug-a-capture").
    Resolved relative to the script's directory.

.PARAMETER InlineCompanion
    If set, also generates a scad-source-inline.scad that embeds the critical
    LWFL companion file content as a reference comment block.

.EXAMPLE
    .\prepare-playground-bundle.ps1 -BundleDir bug-a-capture
    .\prepare-playground-bundle.ps1 -BundleDir bug-b-capture -InlineCompanion
    .\prepare-playground-bundle.ps1 -BundleDir baseline-capture
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$BundleDir,

    [switch]$InlineCompanion
)

$ErrorActionPreference = "Stop"

$bundlePath = Join-Path $PSScriptRoot $BundleDir
if (-not (Test-Path $bundlePath)) {
    Write-Error "Bundle directory not found: $bundlePath"
    exit 1
}

$argsFile = Join-Path $bundlePath "callmain-args.json"
$scadSource = Join-Path $bundlePath "scad-source.scad"
$companionDir = Join-Path $bundlePath "companion-files"

if (-not (Test-Path $argsFile)) {
    Write-Error "callmain-args.json not found in $bundlePath"
    exit 1
}
if (-not (Test-Path $scadSource)) {
    Write-Error "scad-source.scad not found in $bundlePath"
    exit 1
}

$outputDir = Join-Path $bundlePath "playground-ready"
if (Test-Path $outputDir) {
    Remove-Item $outputDir -Recurse -Force
}
New-Item $outputDir -ItemType Directory -Force | Out-Null

# --- Parse -D arguments from callmain-args.json ---

$callMainArgs = Get-Content $argsFile -Raw | ConvertFrom-Json
$defineAssignments = @()

for ($i = 0; $i -lt $callMainArgs.Count; $i++) {
    $arg = $callMainArgs[$i]
    if ($arg -eq "-D" -and ($i + 1) -lt $callMainArgs.Count) {
        $assignment = $callMainArgs[$i + 1]
        $i++

        # Convert from CLI format (var=value) to SCAD assignment (var = value;)
        if ($assignment -match '^(\$?\w+)=(.*)$') {
            $varName = $Matches[1]
            $value = $Matches[2]

            # Clean up escaped quotes from JSON serialization
            # The JSON has values like: expose_home_button=\"no\"
            # which in PowerShell becomes: expose_home_button="no"
            # We need: expose_home_button = "no";
            $defineAssignments += "$varName = $value;"
        }
    }
}

Write-Host "Parsed $($defineAssignments.Count) parameter overrides from callmain-args.json" -ForegroundColor Cyan

# --- Build the modified SCAD source ---

$originalScad = Get-Content $scadSource -Raw -Encoding UTF8

$overrideBlock = @"

// === PARAMETER OVERRIDES (from captured -D args) ===
// Generated by prepare-playground-bundle.ps1
// These override the defaults defined earlier in the file.
// In OpenSCAD, the last assignment to a variable wins.

$($defineAssignments -join "`n")

// === END PARAMETER OVERRIDES ===
"@

$modifiedScad = $originalScad + "`n" + $overrideBlock

$outputScad = Join-Path $outputDir "scad-source.scad"
[System.IO.File]::WriteAllText($outputScad, $modifiedScad, [System.Text.Encoding]::UTF8)

Write-Host "  Written: $outputScad" -ForegroundColor Green

# --- Copy companion files ---

if (Test-Path $companionDir) {
    Copy-Item "$companionDir\*" $outputDir -Recurse -Force
    $fileCount = (Get-ChildItem $outputDir -Recurse -File).Count - 1  # minus the scad file
    Write-Host "  Copied $fileCount companion files to playground-ready/" -ForegroundColor Green
} else {
    Write-Host "  No companion-files directory found (SCAD may be self-contained)" -ForegroundColor Yellow
}

# --- Verify critical companion file ---

$lwflFile = Join-Path $outputDir "Cases and App Specifics\iPad 7,8,9\Fintie-equivalent Case\LWFL\openings_and_additions.txt"
if (Test-Path $lwflFile) {
    Write-Host "  [OK] LWFL companion file present at expected path" -ForegroundColor Green
} else {
    Write-Warning "  [WARN] LWFL companion file NOT found at expected path"
    Write-Warning "  The playground may not be able to resolve 'include' paths"
}

# --- Optional: inline companion data ---

if ($InlineCompanion) {
    $inlineOutput = Join-Path $outputDir "scad-source-inline.scad"

    # Find all openings_and_additions.txt files that might be relevant
    $lwflCompanion = $null
    $standardCompanion = $null

    $lwflPath = Join-Path $outputDir "Cases and App Specifics\iPad 7,8,9\Fintie-equivalent Case\LWFL\openings_and_additions.txt"
    $standardPath = Join-Path $outputDir "Standard Openings and Additions\openings_and_additions.txt"

    if (Test-Path $lwflPath) {
        $lwflCompanion = Get-Content $lwflPath -Raw -Encoding UTF8
    }
    if (Test-Path $standardPath) {
        $standardCompanion = Get-Content $standardPath -Raw -Encoding UTF8
    }

    $inlineHeader = @"

// === COMPANION FILE DATA (inlined for single-file playground use) ===
// If the playground cannot load companion files from the directory tree,
// you may need to modify the SCAD source's include/use statements to
// read from inline data instead. The original file contents are preserved
// below as reference.
//
"@

    if ($lwflCompanion) {
        $inlineHeader += @"

// --- BEGIN: Cases and App Specifics/iPad 7,8,9/Fintie-equivalent Case/LWFL/openings_and_additions.txt ---
/*
$lwflCompanion
*/
// --- END: LWFL/openings_and_additions.txt ---

"@
    }

    if ($standardCompanion) {
        $inlineHeader += @"

// --- BEGIN: Standard Openings and Additions/openings_and_additions.txt ---
/*
$standardCompanion
*/
// --- END: Standard Openings and Additions/openings_and_additions.txt ---

"@
    }

    $inlineScad = $modifiedScad + "`n" + $inlineHeader
    [System.IO.File]::WriteAllText($inlineOutput, $inlineScad, [System.Text.Encoding]::UTF8)

    Write-Host "  Written: $inlineOutput (with inlined companion data)" -ForegroundColor Green
}

# --- Summary ---

Write-Host "`n  Playground bundle ready: $outputDir" -ForegroundColor Cyan

# Show key parameters that differ between bundles
$keyParams = $defineAssignments | Where-Object {
    $_ -match "expose_home_button" -or $_ -match "expose_upper_message_bar"
}
if ($keyParams) {
    Write-Host "  Key parameters:" -ForegroundColor Yellow
    foreach ($p in $keyParams) {
        Write-Host "    $p" -ForegroundColor Yellow
    }
}

Write-Host ""
