"""Template for the .scad file header."""

from __future__ import annotations

from datetime import date


def render_header(
    project_name: str,
    source_dir: str,
    generated_by: str = "forge-cad-to-parametric v0.1.0",
) -> str:
    today = date.today().isoformat()
    return f"""// {project_name} — Parametric OpenSCAD
// Generated by: {generated_by}
// Source:       {source_dir}
// Date:         {today}
//
// Compatible with openscad-assistive-forge:
//   https://openscad-assistive-forge.pages.dev/
//
// License: This generated file inherits the license of the source project.
//
// ─────────────────────────────────────────────────────────
// CUSTOMIZER USAGE
//   Open in OpenSCAD and use View → Customizer to adjust
//   parameters. Or load into openscad-assistive-forge for
//   browser-based customization and STL export.
//
// RENDER MODES
//   assembly  — full assembled model (default)
//   body_only — base solid without pocket fills or features
//   exploded  — components offset for inspection
// ─────────────────────────────────────────────────────────

$fn = 64; // Circle resolution (increase for smoother curves, decrease for speed)

"""
